name: ðŸš€ Deploy via FTP

on:
  push:
    branches:
      - main   # Tá»± Ä‘á»™ng deploy khi push lÃªn nhÃ¡nh main

jobs:
  ftp-deploy:
    name: ðŸ“‚ Upload to Hosting via FTP
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: ðŸ“¤ Deploy files via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          port: ${{ secrets.FTP_PORT }}
          server-dir: /home/uojnvwmnhosting/public_html/
          local-dir: /dist/
          exclude: |
            **/.git*
            **/.github*
            **/node_modules/**
